# Generated by Django 5.0 on 2023-12-23 14:58

import django.db.models.deletion
import extensions.path_manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_artist_userip'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='نام')),
            ],
            options={
                'verbose_name': 'سبک',
                'verbose_name_plural': 'سبک ها',
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='نام')),
                ('file_320', models.FileField(blank=True, null=True, upload_to=extensions.path_manager.create_songs_file_path, verbose_name='کیفیت 320')),
                ('file_128', models.FileField(blank=True, null=True, upload_to=extensions.path_manager.create_songs_file_path, verbose_name='کیفیت 128')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='users.artist', verbose_name='خواننده')),
                ('genre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='songs', to='songs.genre', verbose_name='سبک')),
                ('viewers_by_ip', models.ManyToManyField(blank=True, default='192.168.0.1', related_name='videos', to='users.userip', verbose_name='بازدیدکنندگان بر اساس IP')),
            ],
            options={
                'verbose_name': 'آهنگ',
                'verbose_name_plural': 'آهنگ ها',
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liked_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='songs.song', verbose_name='آهنگ')),
            ],
            options={
                'verbose_name': 'لایک',
                'verbose_name_plural': 'لایک ها',
            },
        ),
    ]
