# Generated by Django 5.0 on 2023-12-25 12:58

import extensions.path_manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='file_128',
        ),
        migrations.RemoveField(
            model_name='song',
            name='file_320',
        ),
        migrations.AddField(
            model_name='song',
            name='cover_image',
            field=models.FileField(blank=True, null=True, upload_to=extensions.path_manager.create_cover_image_path, verbose_name='کاور موزیک'),
        ),
        migrations.AddField(
            model_name='song',
            name='file',
            field=models.FileField(default=1, upload_to=extensions.path_manager.create_songs_file_path, verbose_name='فایل موزیک'),
            preserve_default=False,
        ),
    ]
