# Generated by Django 5.0 on 2023-12-23 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=11, unique=True, verbose_name='شماره همراه')),
                ('otp_code', models.CharField(max_length=10, null=True, verbose_name='کد یکبار مصرف')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='درخواست')),
                ('expire_at', models.DateTimeField(editable=False, verbose_name='انقضا')),
            ],
            options={
                'verbose_name': 'کد یکبار مصرف',
                'verbose_name_plural': 'کدهای یکبار مصرف',
            },
        ),
    ]
